In [88]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras import layers
from tensorflow import keras

In [89]:
mydata=pd.read_csv(r"C:\Users\ANKIT SINGH\Desktop\internship\DataSets-master\500_Person_Gender_Height_Weight_Index.csv")

In [90]:
mydata[:2]

Gender  Height  Weight  Index
0   Male     174      96      4
1   Male     189      87      2

In [91]:
X=mydata.iloc[:,0:3]
Y=mydata.iloc[:,3]   #output is index

In [134]:
X      

Gender  Height  Weight
0         0     174      96
1         0     189      87
2         1     185     110
3         1     195     104
4         0     149      61
5         0     189     104
6         0     147      92
7         0     154     111
8         0     174      90
9         1     169     103
10        0     195      81
11        1     159      80
12        1     192     101
13        0     155      51
14        0     191      79
15        1     153     107
16        1     157     110
17        0     140     129
18        0     144     145
19        0     172     139
20        0     157     110
21        1     153     149
22        1     169      97
23        0     185     139
24        1     172      67
25        1     151      64
26        0     190      95
27        0     187      62
28        1     163     159
29        0     179     152
..      ...     ...     ...
470       0     147     142
471       0     154     112
472       1     178      65
473       0     195     153
474       1     167      79
475       0     183     131
476       1     164     142
477       0     167      64
478       1     151      55
479       1     147     107
480       1     155     115
481       1     172     108
482       1     142      86
483       0     146      85
484       1     188     115
485       0     173     111
486       1     160     109
487       0     187      80
488       0     198     136
489       1     179     150
490       1     164      59
491       1     146     147
492       1     198      50
493       1     170      53
494       0     152      98
495       1     150     153
496       1     184     121
497       1     141     136
498       0     150      95
499       0     173     131

[500 rows x 3 columns]

In [135]:
Y  #index values separate

0      4
1      2
2      4
3      3
4      3
5      3
6      5
7      5
8      3
9      4
10     2
11     4
12     3
13     2
14     2
15     5
16     5
17     5
18     5
19     5
20     5
21     5
22     4
23     5
24     2
25     3
26     3
27     1
28     5
29     5
      ..
470    5
471    5
472    2
473    5
474    3
475    4
476    5
477    2
478    2
479    5
480    5
481    4
482    5
483    4
484    4
485    4
486    5
487    2
488    4
489    5
490    2
491    5
492    0
493    1
494    5
495    5
496    4
497    5
498    5
499    5
Name: Index, Length: 500, dtype: int64

In [137]:
Index_name=pd.Series(["Extremely Weak","Weak","Normal","Overweight","Obesity","Extreme Obesity"])
Index_name

0     Extremely Weak
1               Weak
2             Normal
3         Overweight
4            Obesity
5    Extreme Obesity
dtype: object

In [138]:
X["Gender"]=X["Gender"].map({"Male":0,"Female":1})

In [94]:
XA=X.values
YA=Y.values

In [95]:
XA

array([[  0, 174,  96],
       [  0, 189,  87],
       [  1, 185, 110],
       ...,
       [  1, 141, 136],
       [  0, 150,  95],
       [  0, 173, 131]], dtype=int64)

In [96]:
YA

array([4, 2, 4, 3, 3, 3, 5, 5, 3, 4, 2, 4, 3, 2, 2, 5, 5, 5, 5, 5, 5, 5,
       4, 5, 2, 3, 3, 1, 5, 5, 5, 1, 1, 5, 5, 4, 3, 4, 5, 2, 4, 5, 2, 5,
       4, 2, 4, 4, 3, 5, 5, 1, 5, 4, 4, 3, 4, 5, 3, 5, 0, 5, 0, 2, 5, 5,
       4, 2, 4, 4, 2, 4, 5, 2, 3, 4, 4, 4, 4, 0, 3, 5, 3, 4, 5, 0, 5, 5,
       5, 5, 5, 3, 3, 2, 4, 5, 4, 5, 1, 0, 4, 5, 5, 4, 4, 4, 5, 5, 4, 3,
       4, 5, 4, 2, 4, 3, 2, 5, 5, 5, 4, 4, 4, 5, 5, 4, 4, 4, 5, 2, 5, 2,
       5, 4, 5, 5, 5, 3, 5, 5, 2, 4, 5, 5, 5, 4, 3, 5, 3, 3, 0, 3, 3, 5,
       5, 4, 3, 5, 3, 4, 2, 2, 3, 5, 4, 2, 4, 5, 3, 2, 4, 5, 5, 4, 4, 4,
       4, 3, 5, 3, 3, 4, 4, 2, 3, 3, 5, 3, 5, 4, 5, 5, 4, 5, 5, 5, 4, 4,
       5, 5, 1, 3, 4, 4, 5, 4, 5, 4, 3, 4, 4, 5, 5, 5, 0, 5, 5, 5, 5, 5,
       2, 5, 4, 5, 0, 5, 3, 4, 5, 5, 4, 2, 3, 3, 4, 3, 5, 5, 2, 5, 3, 2,
       1, 5, 0, 5, 3, 5, 3, 4, 3, 5, 5, 5, 5, 2, 4, 5, 5, 4, 5, 5, 5, 2,
       4, 5, 5, 5, 5, 1, 5, 5, 4, 0, 3, 3, 4, 2, 3, 1, 1, 5, 5, 4, 4, 4,
       4, 5, 2, 5, 4, 3, 3, 4, 5, 5, 2, 4, 3, 4, 5,

In [97]:
print("Type od XA {} and Type of YA {}".format(type(XA),type(YA)))

Type od XA <class 'numpy.ndarray'> and Type of YA <class 'numpy.ndarray'>


In [98]:
Yc=tf.keras.utils.to_categorical(YA,num_classes=6,dtype="float32")
Yc

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       ...,
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)

In [99]:
type(Yc)

numpy.ndarray

In [100]:
from sklearn.model_selection import train_test_split

In [123]:
xtrain,xtest,ytrain,ytest=train_test_split(XA,Yc,test_size=.30,random_state=101)

In [124]:
model=tf.keras.Sequential()

In [125]:
model.add(layers.Dense(20,input_dim=3,activation="relu"))
model.add(layers.Dense(20,activation="relu"))
model.add(layers.Dense(6,activation='softmax'))

#compiling model
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=['accuracy'])

In [126]:
model.fit(xtrain,ytrain,epochs=500,batch_size=100)

Epoch 1/500
350/350 [==============================] - 0s 648us/sample - loss: 41.8922 - acc: 0.0457
Epoch 2/500
350/350 [==============================] - 0s 40us/sample - loss: 35.3408 - acc: 0.0800
Epoch 3/500
350/350 [==============================] - 0s 40us/sample - loss: 29.4652 - acc: 0.1857
Epoch 4/500
350/350 [==============================] - 0s 40us/sample - loss: 24.2412 - acc: 0.2229
Epoch 5/500
350/350 [==============================] - 0s 40us/sample - loss: 19.8543 - acc: 0.1657
Epoch 6/500
350/350 [==============================] - 0s 34us/sample - loss: 15.3652 - acc: 0.2429
Epoch 7/500
350/350 [==============================] - 0s 46us/sample - loss: 11.6356 - acc: 0.4000
Epoch 8/500
350/350 [==============================] - 0s 43us/sample - loss: 9.9087 - acc: 0.5314
Epoch 9/500
350/350 [==============================] - 0s 43us/sample - loss: 9.6522 - acc: 0.4886
Epoch 10/500
350/350 [==============================] - ETA: 0s - loss: 6.5148 - acc: 0.490 - 0s 43us

350/350 [==============================] - 0s 31us/sample - loss: 0.7289 - acc: 0.6629
Epoch 83/500
350/350 [==============================] - 0s 34us/sample - loss: 0.7245 - acc: 0.6629
Epoch 84/500
350/350 [==============================] - 0s 29us/sample - loss: 0.7224 - acc: 0.6686
Epoch 85/500
350/350 [==============================] - 0s 34us/sample - loss: 0.7214 - acc: 0.6743
Epoch 86/500
350/350 [==============================] - 0s 34us/sample - loss: 0.7217 - acc: 0.6771
Epoch 87/500
350/350 [==============================] - 0s 40us/sample - loss: 0.7155 - acc: 0.6600
Epoch 88/500
350/350 [==============================] - 0s 31us/sample - loss: 0.7146 - acc: 0.6657
Epoch 89/500
350/350 [==============================] - 0s 34us/sample - loss: 0.7153 - acc: 0.6714
Epoch 90/500
350/350 [==============================] - 0s 39us/sample - loss: 0.7151 - acc: 0.6629
Epoch 91/500
350/350 [==============================] - 0s 34us/sample - loss: 0.7091 - acc: 0.6657
Epoch 92/500


350/350 [==============================] - 0s 34us/sample - loss: 0.6441 - acc: 0.7114
Epoch 164/500
350/350 [==============================] - 0s 34us/sample - loss: 0.6439 - acc: 0.7114
Epoch 165/500
350/350 [==============================] - 0s 37us/sample - loss: 0.6423 - acc: 0.7057
Epoch 166/500
350/350 [==============================] - 0s 34us/sample - loss: 0.6465 - acc: 0.7057
Epoch 167/500
350/350 [==============================] - 0s 31us/sample - loss: 0.6405 - acc: 0.7143
Epoch 168/500
350/350 [==============================] - 0s 34us/sample - loss: 0.6435 - acc: 0.7029
Epoch 169/500
350/350 [==============================] - 0s 40us/sample - loss: 0.6473 - acc: 0.6914
Epoch 170/500
350/350 [==============================] - 0s 34us/sample - loss: 0.6475 - acc: 0.7114
Epoch 171/500
350/350 [==============================] - 0s 34us/sample - loss: 0.6401 - acc: 0.7086
Epoch 172/500
350/350 [==============================] - 0s 34us/sample - loss: 0.6415 - acc: 0.7057
Epoc

350/350 [==============================] - 0s 43us/sample - loss: 0.6127 - acc: 0.7114
Epoch 244/500
350/350 [==============================] - 0s 40us/sample - loss: 0.6143 - acc: 0.7114
Epoch 245/500
350/350 [==============================] - 0s 37us/sample - loss: 0.6146 - acc: 0.7257
Epoch 246/500
350/350 [==============================] - 0s 40us/sample - loss: 0.6137 - acc: 0.7257
Epoch 247/500
350/350 [==============================] - 0s 34us/sample - loss: 0.6229 - acc: 0.7114
Epoch 248/500
350/350 [==============================] - 0s 43us/sample - loss: 0.6150 - acc: 0.7000
Epoch 249/500
350/350 [==============================] - 0s 34us/sample - loss: 0.6119 - acc: 0.7114
Epoch 250/500
350/350 [==============================] - 0s 31us/sample - loss: 0.6114 - acc: 0.7343
Epoch 251/500
350/350 [==============================] - 0s 37us/sample - loss: 0.6121 - acc: 0.7200
Epoch 252/500
350/350 [==============================] - 0s 34us/sample - loss: 0.6108 - acc: 0.7314
Epoc

350/350 [==============================] - 0s 40us/sample - loss: 0.5939 - acc: 0.7057
Epoch 324/500
350/350 [==============================] - 0s 37us/sample - loss: 0.5905 - acc: 0.7343
Epoch 325/500
350/350 [==============================] - 0s 43us/sample - loss: 0.5936 - acc: 0.7229
Epoch 326/500
350/350 [==============================] - 0s 34us/sample - loss: 0.5989 - acc: 0.7257
Epoch 327/500
350/350 [==============================] - 0s 43us/sample - loss: 0.5928 - acc: 0.7200
Epoch 328/500
350/350 [==============================] - 0s 46us/sample - loss: 0.5878 - acc: 0.7400
Epoch 329/500
350/350 [==============================] - 0s 40us/sample - loss: 0.5958 - acc: 0.7286
Epoch 330/500
350/350 [==============================] - 0s 43us/sample - loss: 0.5875 - acc: 0.7400
Epoch 331/500
350/350 [==============================] - 0s 49us/sample - loss: 0.5915 - acc: 0.7314
Epoch 332/500
350/350 [==============================] - 0s 46us/sample - loss: 0.5937 - acc: 0.7229
Epoc

350/350 [==============================] - 0s 34us/sample - loss: 0.5819 - acc: 0.7200
Epoch 405/500
350/350 [==============================] - 0s 40us/sample - loss: 0.5682 - acc: 0.7429
Epoch 406/500
350/350 [==============================] - 0s 34us/sample - loss: 0.5847 - acc: 0.7400
Epoch 407/500
350/350 [==============================] - 0s 43us/sample - loss: 0.5730 - acc: 0.7343
Epoch 408/500
350/350 [==============================] - 0s 43us/sample - loss: 0.5743 - acc: 0.7400
Epoch 409/500
350/350 [==============================] - 0s 43us/sample - loss: 0.5763 - acc: 0.7286
Epoch 410/500
350/350 [==============================] - 0s 40us/sample - loss: 0.5749 - acc: 0.7400
Epoch 411/500
350/350 [==============================] - 0s 40us/sample - loss: 0.5737 - acc: 0.7286
Epoch 412/500
350/350 [==============================] - 0s 40us/sample - loss: 0.5688 - acc: 0.7429
Epoch 413/500
350/350 [==============================] - 0s 43us/sample - loss: 0.5831 - acc: 0.7543
Epoc

350/350 [==============================] - 0s 40us/sample - loss: 0.5666 - acc: 0.7400
Epoch 485/500
350/350 [==============================] - 0s 37us/sample - loss: 0.5598 - acc: 0.7400
Epoch 486/500
350/350 [==============================] - ETA: 0s - loss: 0.5763 - acc: 0.800 - 0s 31us/sample - loss: 0.5608 - acc: 0.7629
Epoch 487/500
350/350 [==============================] - 0s 46us/sample - loss: 0.5738 - acc: 0.7400
Epoch 488/500
350/350 [==============================] - 0s 43us/sample - loss: 0.5680 - acc: 0.7486
Epoch 489/500
350/350 [==============================] - 0s 37us/sample - loss: 0.5670 - acc: 0.7371
Epoch 490/500
350/350 [==============================] - 0s 37us/sample - loss: 0.5624 - acc: 0.7314
Epoch 491/500
350/350 [==============================] - 0s 40us/sample - loss: 0.5701 - acc: 0.7629
Epoch 492/500
350/350 [==============================] - 0s 43us/sample - loss: 0.5694 - acc: 0.7400
Epoch 493/500
350/350 [==============================] - 0s 37us/sa

In [148]:
score=model.evaluate(xtest,ytest)

150/150 [==============================] - 0s 62us/sample - loss: 0.4804 - acc: 0.8000


In [149]:
s=score[1]
s*100

80.0000011920929

In [150]:
import numpy as np

In [151]:
a=[0,-1,2.,3]

In [152]:
s=tf.nn.softmax(a)

In [154]:
with tf.Session() as sess:
    print(sess.run(s))
    #print(sess.run(a))

[0.03467109 0.01275478 0.25618663 0.69638747]
