In [117]:
import numpy as np

In [118]:
def mysigmodfunction(x):
    return 1/(1+np.exp(-x))

In [119]:
X_input=np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
Y_out=np.array([[0],[1],[1],[0]])

In [120]:
X_input

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [121]:
Y_out

array([[0],
       [1],
       [1],
       [0]])

In [122]:
w=np.random.random((3,1))-1

In [123]:
w   #random value each time

array([[-0.25119612],
       [-0.50149299],
       [-0.77520335]])

In [124]:
w=np.random.random((3,1))-1 #sudo random generator

In [125]:
w   

array([[-0.80193714],
       [-0.23946929],
       [-0.83088916]])

In [126]:
np.random.seed(10)     #this method initialize the basic random number generator
w

array([[-0.80193714],
       [-0.23946929],
       [-0.83088916]])

In [127]:
w=np.random.random((3,1))-1    #sudo random generator
print("weight are :")
print(w)

weight are :
[[-0.22867936]
 [-0.97924805]
 [-0.36635177]]


In [128]:
def derivate_sigmod(x):
     return x*(1-x)

In [129]:
for i in range(5000):
    input_layer=X_input
    Aout=mysigmodfunction(np.dot(input_layer,w)) 
    error=Y_out-Aout
    Weight_adjust=error*derivate_sigmod(Aout)
    w +=np.dot(input_layer.T,Weight_adjust)
print("Aout")
print(Aout)
print("W")
print(w)

Aout
[[0.01379078]
 [0.98876501]
 [0.99088905]
 [0.01118902]]
W
[[ 8.95920059]
 [-0.21170101]
 [-4.26997241]]


In [130]:
from sklearn.metrics import mean_squared_error

In [131]:
error=mean_squared_error(Y_out,Aout)*100
error

0.013115359429072337

In [135]:
Xtest=np.array([[1],[1],[1]])
np.dot(w.T,Xtest)

array([[4.47752717]])

In [136]:
X_test

array([[1],
       [1],
       [1]])

In [137]:
w

array([[ 8.95920059],
       [-0.21170101],
       [-4.26997241]])